# Physics 404/604

## Computational Physics (Spring 2019)

## BPB-250, Mon./Wed. 1:00-2:15 pm

| Instructor | Prof. Zhaohuan Zhu                 |
| ---------- | :--------------------------------- |
| Email      | zhaohuan.zhu@unlv.edu              |
| Website    | http://www.physics.unlv.edu/~zhzhu |
| Office     | BPB 245                            |



# Matrix Computing

Matrix computing is used extensively in physics, engineering, math, ...

## 1) Solve a system of linear equations

\begin{eqnarray}
9x_{1}+13x_{2}+5x_{3}+2x_{4}=7\\
x_{1}+11x_{2}+7x_{3}+6x_{4}=8\\
3x_{1}+7x_{2}+4x_{3}+x_{4}=9\\
6x_{1}+1x_{2}+7x_{3}+10x_{4}=10
\end{eqnarray}

We can write the equations in the matrix form
\begin{equation}
\begin{bmatrix} 9 & 13 & 5 & 2 \\ 
          1 & 11 & 7 & 6 \\ 
          3 & 7 & 4 & 1 \\ 
          6 & 1 & 7 & 10\end{bmatrix} \left[ \begin{array}{c} x_{1} \\ x_{2} \\ x_{3} \\ x_{4} \end{array}\right] = \left[ \begin{array}{c} 7 \\ 8 \\ 9 \\ 10 \end{array}\right]
\end{equation}


Generally, 
\begin{equation}
A\bf{x}=\bf{b}
\end{equation}
where A is known N$\times$N matrix, $\bf{x}$ is an unknown vector of length N, and $\bf{b}$ is a known vector of length N.

Several ways to solve it:   
* solve it directly by Gaussian elimination or lower-upper (LU) decomposition  
* invese A and $\bf{x}=A^{-1}\bf{b}$



## Prerequisite: Use arrays

Be careful with arrays 

1) track indices 
![From textbook](http://physics.oregonstate.edu/~landaur/Books/CPbook/eBook/Notebooks/HTML/Figs/Fig6_3.png)
Row-major order used for matrix storage in Python, C and Java : 
a[3,3] (a[row, column])is stored as a[0,0], a[0,1], a[0,2], a[1,0], a[1,1], a[1,2], a[2,0], ...

2) memory usage (4D array with 100 elements in each direction)

In [7]:
### we can use list to represent array
a=[1,2,3]

### but normally use Numpy package, has a lot more support for numerical arrays

import numpy as np
vector1 = np.array([1, 2, 3, 4, 5])
matrix1 = np.array([[0,2],[1,3]])
print(matrix1)

# How to print the element at the first row and the second column
print(matrix1[0,1])

[[0 2]
 [1 3]]
2


In [8]:

#Notice that * operation is element operation
print(matrix1*matrix1)

[[0 4]
 [1 9]]


In [9]:
import numpy as np
np.arange(12)  # list of 12 ints

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np.arange(12).reshape(3,4) # create, shape to 3x4 array (3 rows, 4 columns)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a=np.arange(12).reshape(3,4)
a.shape # shape 

(3, 4)

In [12]:
a.ndim # dimension

2

In [13]:
a.size # size of a (number of elements)

12

In [14]:
a.T  # transpose method

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [15]:
# Slicing
print(a[:2, :])  # 0:2 means 0 and 1, first two rows

stuff= np.zeros(10, float) # one way to initialize an array
t=np.arange(4)
stuff[3:7]=np.sqrt(t+1) #notice that it can imput an array and output an array.
print(stuff)

[[0 1 2 3]
 [4 5 6 7]]
[0.         0.         0.         1.         1.41421356 1.73205081
 2.         0.         0.         0.        ]


In [16]:
# initialize array with some value
stuff= np.ones(10, float)*3.
print(stuff)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [17]:
# Write a program to carry out the dot product of matrix A and vector B
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])
c=np.zeros(4)

for i in range(4):
    for j in range(4):
        # please finish this line
        
print(c)



[232. 218. 123. 213.]


### Several array products

In [18]:
import numpy as np
np.dot(a,b)

array([232., 218., 123., 213.])

In [19]:
# array can be float, complex types... 
# If you want matrix dot 
matrix1 = np.array([[0.,1.],[1.,3.]])
print(np.dot(matrix1,matrix1))

[[ 1.  3.]
 [ 3. 10.]]


In [20]:
# if you want element product
print(matrix1*matrix1)

[[0. 1.]
 [1. 9.]]


In [21]:
#or
print(np.multiply(matrix1,matrix1))

[[0. 1.]
 [1. 9.]]


## Use NumPy's linalg Package

### Solve A$\bf{x}$=$\bf{b}$

In [22]:
import numpy as np
A= np.array([[1.,2.,3.],[22.,32.,42],[55.,66.,100.]])
b = np.array([1.,2.,3.])
print(A,b)

[[  1.   2.   3.]
 [ 22.  32.  42.]
 [ 55.  66. 100.]] [1. 2. 3.]


In [23]:
# Method 1. Solve Ax=b directly
x=np.linalg.solve(A,b)
print('x=',x)
print('Residual= ',np.dot(A,x)-b)

x= [-1.4057971  -0.1884058   0.92753623]
Residual=  [ 0.00000000e+00 -7.10542736e-15  0.00000000e+00]


In [24]:
# Method 2. Solve Ax=b using the inversion of A
B=np.linalg.inv(A)
print(np.dot(B,b))

[-1.4057971  -0.1884058   0.92753623]


In [25]:
print('x=', np.dot(B,b))
print('Residual= ',np.dot(A,np.dot(B,b))-b)

x= [-1.4057971  -0.1884058   0.92753623]
Residual=  [4.44089210e-16 0.00000000e+00 1.42108547e-14]


In [ ]:
# Use above two methods to solve 2y+z=-8, x-2y-3z=0, -x+y+2z=3


## LU decomposition

To solve Ax=b,   
* to decompose A to A=L$\cdot$U, where matrix L is lower triangular and matrix U is upper triangular
* L $\cdot$ (U $\cdot$ x)=b, it is equivalent to L$\cdot$y=b, U$\cdot$x=y

We define L as

\begin{bmatrix} 1 & 0 & 0 &... & 0 \\ 
          \alpha_{21} & 1 &  0 &... & 0 \\
          \ddots & \ddots & \ddots\\
          \alpha_{i1} & ... & \alpha_{i,i-1} & 1 & ... \\ 
          \ddots & \ddots & \ddots & \ddots \\
          \alpha_{n1} & ... & ... & ... & 1\end{bmatrix} 

and U as
\begin{bmatrix} \beta_{11} & \beta_{12} & ... & \beta_{1j} & ... \\ 
          0 & \beta_{22} &  ... &... & ... \\
          0  & 0 & \ddots & \ddots\\
          0  & 0  & \beta_{jj} & ... & ... \\ 
          0 & 0  & 0 & \ddots \\
          0 & 0 & 0  & 0 & \beta_{nn}\end{bmatrix} 

So we have
\begin{equation}
a_{ij}=\begin{cases} \sum_{k=1}^{i-1}\alpha_{ik}\beta_{kj}+\beta_{ij}  \qquad i\leq j,\\
                          \sum_{k=1}^{j-1}\alpha_{ik}\beta_{kj}+\alpha_{ij}\beta_{jj} \qquad i> j, \end{cases}
\end{equation}

Or we have
\begin{eqnarray}
\beta_{ij}=a_{ij}-\sum_{k=1}^{i-1}\alpha_{ik}\beta_{kj} \qquad i=1,2,...j, \quad j=1,...n\\
\alpha_{ij}=\frac{1}{\beta_{jj}}[a_{ij}-\sum_{k=1}^{j-1}\alpha_{ik}\beta_{kj}] \qquad i=j+1,...n
\end{eqnarray}

The sequence to solve:   
$\beta_{11}$, $\alpha_{21}$, ... ,$\alpha_{n1}$,  
$\beta_{12}$, $\beta_{22}$, $\alpha_{32}$, ... ,$\alpha_{n2}$,  
$\beta_{13}$, $\beta_{23}$, $\beta_{33}$, $\alpha_{43}$, ... ,$\alpha_{n3}$,  
...

What if $\beta_{jj}$ is zero?  
Needs pivoting: switch rows



In [30]:
import numpy as np
#============================================================================
def LUFactor(a, ipivot, n):
# Copy right, code from Titus textbook. 
#----------------------------------------------------------------------------
#  Performs LU factorization of (n x n) matrix a (diag(L) = 1). On exit,
#  replaces upper triangle and diagonal with U, and lower triangle, with L.
#  Uses partial pivoting on columns.
#  a      - coefficient matrix (n x n); LU decomposition on exit
#  ipivot - array of pivot row indexes (output)
#  det    - determinant of coefficient matrix (output).
#----------------------------------------------------------------------------
   det = 1e0
   for j in range(n):                                 # loop over columns
      for i in range(j):                             # elements of matrix U
         sum = a[i][j]
         for k in range(i): sum -= a[i][k]*a[k][j]
         a[i][j] = sum

      amax = 0e0
      for i in range(j,n):                           # elements of matrix L
         sum = a[i][j]                                 # undivided by pivot
         for k in range(j): sum -= a[i][k]*a[k][j]
         a[i][j] = sum
                                                            # determine pivot
         if (amax < np.fabs(a[i][j])): amax = np.fabs(a[i][j]); imax = i

      if (amax == 0e0): print("LUFactor: singular matrix !"); return 0e0

      ipivot[j] = imax                                # store pivot row index
                                                # interchange rows imax and j
      if (imax != j):                           # to put pivot on diagonal
         det = -det
         for k in range(n):
            t = a[imax][k]; a[imax][k] = a[j][k]; a[j][k] = t

      det *= a[j][j]                        # multiply determinant with pivot

      t = 1e0/a[j][j]                         # divide elements of L by pivot
      for i in range(j+1,n): a[i][j] *= t

   return det

#============================================================================
def LUSystem(a, ipivot, b, n):
# Copy right, code from Titus textbook. 
#----------------------------------------------------------------------------
#  Solves linear system a x = b of order n by LU factorization.
#  a      - LU decomposition of coefficient matrix (returned by LUFactor)
#  ipivot - array of pivot row indexes (input)
#  b      - vector of constant terms (input); solution x (on exit)
#----------------------------------------------------------------------------
   for i in range(n):                                     # solves Ly = b
      sum = b[int(ipivot[i])]
      b[int(ipivot[i])] = b[i]
      for j in range(i): sum -= a[i][j]*b[j]
      b[i] = sum

   for i in range(n-1,-1,-1):                                    # solves Ux = y
      sum = b[i]
      for j in range(i+1,n): sum -= a[i][j]*b[j]
      b[i] = sum/a[i][i]


In [31]:
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])
aa=np.copy(a)    #deep copy of an array
bb=np.copy(b)    #deep copy of an array
ipivot=np.zeros(4)
de=LUFactor(a,ipivot,4)
LUSystem(a,ipivot,b,4)
print(b)

print(np.dot(aa,b)-bb)

[ 0.1729798  -0.87689394  4.13194444 -1.9084596 ]
[-3.55271368e-15 -1.77635684e-15 -1.77635684e-15 -7.10542736e-15]


In [32]:
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])

# Solve Ax=b directly
x=np.linalg.solve(a,b)
print('x=',x)
print(np.dot(a,x)-b)

x= [ 0.1729798  -0.87689394  4.13194444 -1.9084596 ]
[-3.55271368e-15  0.00000000e+00  0.00000000e+00  0.00000000e+00]


## Gauss-Seidel Iterative Method

Make a guess and do correction

\begin{eqnarray}
a_{11}x_{1}+a_{12}x_{2}+...+a_{1n}x_{n}=b_{1}\\
a_{21}x_{1}+a_{22}x_{2}+...+a_{2n}x_{n}=b_{2}\\
...\\
a_{n1}x_{1}+a_{n2}x_{2}+...+a_{nn}x_{n}=b_{n}
\end{eqnarray}

We assume the diagonal elements $a_{jj}$ to be nonzero, or, we switch the equations to make them nonzero. We can rewrite it as

\begin{eqnarray}
x_{1} = t_{1}+s_{12}x_{2}+...+s_{1n}x_{n}\\
x_{2} = s_{21}x_{1}+t_{2}+...+s_{2n}x_{n}\\
...\\
x_{n} = s_{n1}x_{1}+s_{n2}x_{2}+...t_{n}
\end{eqnarray}
So we can write it as the matrix form  
$\bf{x}$=S$\bf{x}$+t  
With initial guess $x^{(0)}=t$, we can build the solution using the recurrence relation  
$\bf{x^{(k)}}$=S$\bf{x^{k-1}}$+t, k=1,2,...
or
\begin{equation}
x_{i}^{(k)}=\sum_{j\neq i}^{n}s_{ij}x_{j}^{(k-1)}+t_{i}\qquad i=1,2,...,n
\end{equation}
This is called Jacobi method. With a slight modification, we get a more efficient
so-called Gauss-Seidel method:
\begin{equation}
x_{i}^{(k)}=\sum_{j=1}^{i-1}s_{ij}x_{j}^{(k)}+\sum_{j=i+1}^{n}s_{ij}x_{j}^{(k-1)}+t_{i}\qquad i=1,2,...,n
\end{equation}
Use the most recently updated solution components $x_{i}^{k}$ instead of those from previous steps, as soon as they become available. 

The iteration stops when 
\begin{equation}
max_{i}|\Delta_{i}^{(k)}/x_{i}^{k}|\leq \epsilon
\end{equation}

Convergence: 
A must be strictly diagonally dominant 
\begin{equation}
|a_{ii}|>\sum_{j\neq i}|a_{ij}|,\qquad i=1,2,...,n|
\end{equation}
In reality, use
\begin{equation}
|a_{ii}|>max_{j\neq i}|a_{ij}|,\qquad i=1,2,...,n|
\end{equation}
There are situations that the solution won't converge.

For normal system, having a symmetric positive-definite coefficient matrix,
the Gauss-Seidel process is always converging. To make it a normal system
\begin{equation}
A^{T}\cdot A\cdot x=A^{T}\cdot b
\end{equation}

In [46]:

#============================================================================
def GaussSeidel(a, b, x, n, init):
# Copy right, code from Titus textbook. 
#----------------------------------------------------------------------------
#  Solves linear system a x = b by the Gauss-Seidel method.
#  Convergence is ensure by left-multiplying the system with a^T.
#  a    - coefficient matrix (n x n)
#  b    - vector of constant terms
#  x    - initial approximation of solution (input); solution (output)
#  n    - order of system
#  err  - maximum relative error of the solution components
#  init - initialization option: 0 - refines initial approximation 
#                                1 - initializes solution
#----------------------------------------------------------------------------
   eps = 1e-15                                 # relative precision criterion
   itmax = 10000                                    # max no. of iterations

   s = [[0]*(n) for i in range(n)]           # matrices of reduced system
   t = [0]*(n)

   for i in range(n):                         # matrices of normal system
      for j in range(i+1):                      # by multiplication with aT
         s[i][j] = 0e0                            # store result in s and t
         for k in range(n): s[i][j] += a[k][i]*a[k][j]
         s[j][i] = s[i][j]

      t[i] = 0e0
      for j in range(n): t[i] += a[j][i]*b[j]

   for i in range(n):                # matrices s and t of reduced system
      f = -1e0/s[i][i]; t[i] /= s[i][i]
      for j in range(n): s[i][j] *= f

   if (init):
      for i in range(n): x[i] = t[i]                # initialize solution

   for k in range(itmax):                            # loop of iterations
      err = 0e0
      for i in range(n):
         delta = t[i]                                            # correction
         for j in range(n): delta += s[i][j]*x[j]
         x[i] += delta                        # new approximation to solution
         if (x[i]): delta /= x[i]                            # relative error
         if (np.fabs(delta) > err): err = np.fabs(delta)            # maximum error
       #  print('delta,err',delta,err)
            
      if (err <= eps): break                              # check convergence

   if (k > itmax-2): print("GaussSeidel: max. no. of iterations exceeded !")

   return err

In [47]:
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])
x=np.array([1.,1.,1.,1.])

GaussSeidel(a, b, x, 4, 1)
print('x=',x)
print(np.dot(a,x)-b)

x= [ 0.1729798  -0.87689394  4.13194444 -1.9084596 ]
[ 9.23705556e-14  6.75015599e-14 -2.27373675e-13 -3.01980663e-14]


### A bigger matrix

\begin{equation}
[a_{ij}]=[1/(i+j+1)]=\begin{bmatrix} 1 & 1/2 & 1/3 & ... & 1/100 \\ 
          1/2 & 1/3 & 1/4 & ... & 1/101 \\ 
          \ddots \\ 
          1/100 & 1/101 & ... & ...& 1/199\end{bmatrix}
\end{equation}

\begin{equation}
[b_{i}]=[1/(i+1)]=\left[ \begin{array}{c} 1 \\ 1/2 \\ 1/3 \\ ... \\ 1/100 \end{array}\right] 
\end{equation}

Now we want to solve Ax=b

In [39]:
import numpy as np
import time
N=100
A=np.zeros((N,N),float)
B=np.zeros(N,float)
for i in range(N):
    for j in range(N):
        A[i,j]=1./(i+j+1.)
        
for i in range(N):
    B[i]=1./(i+1)

start = time.time()
# write one line of code to solve Ax=B using linalg package 

end = time.time()
print('x=',x)
print('Time ',end-start)

x=np.ones(N)
start2 = time.time()
# write one line of code to solve Ax=B using Gauss-Siedel method 

end2 = time.time()
print('x=',x)
print('Time ',end2-start2)

ipivot=np.zeros(N)
start3 = time.time()
# write two lines of code to solve Ax=B with LU decomposition


end3 = time.time()
print('x=',B)
print('Time ',end3-start3)

x= [ 1.  0.  0.  0.  0.  0.  0.  0. -0. -0. -0.  0.  0.  0. -0. -0.  0. -0.
 -0.  0.  0. -0.  0.  0.  0. -0. -0.  0. -0. -0. -0.  0.  0.  0.  0. -0.
 -0.  0. -0.  0. -0. -0. -0. -0.  0.  0.  0.  0. -0.  0.  0.  0.  0. -0.
  0. -0.  0. -0. -0.  0.  0.  0.  0. -0.  0. -0. -0.  0.  0. -0. -0. -0.
 -0.  0. -0. -0. -0.  0.  0. -0. -0.  0. -0. -0. -0. -0.  0. -0. -0. -0.
 -0.  0.  0. -0. -0. -0.  0.  0.  0.  0.]
Time  0.0010170936584472656
GaussSeidel: max. no. of iterations exceeded !
x= [ 0.8829249   0.04159562  1.50646446 -0.0777201  -0.98090776 -1.22689833
 -1.10667623 -0.8225327  -0.48916825 -0.16606578  0.1188006   0.35470348
  0.54003093  0.67774031  0.7728475   0.83106317  0.85807411  0.85918656
  0.83917096  0.80221698  0.75194663  0.6914561   0.62336949  0.54989545
  0.47288182  0.39386594  0.31411963  0.2346888   0.15642775  0.08002883
  0.0060477  -0.06507498 -0.13299523 -0.19745011 -0.25824452 -0.31523997
 -0.36834516 -0.41750791 -0.46270839 -0.50395345 -0.54127174 -0.57470963
 

## Two masses on a string problem:

The problem is from the textbook "COMPUTATIONAL PHYSICS", 3rd Ed, by RH Landau, MJ Paez, and CC Bordeianu

Very hard to solve analytically.

Write down the equations, and we have 9 variables (treat sin, cos as variables), and 9 nonlinear equations.

\begin{equation}
f_{i}(x_{1},x_{2},...,x_{N})=0, \qquad i=1,2,....,N
\end{equation}

\begin{equation}
f(y)=\left[ \begin{array}{c} f_{1}(\bf{y}) \\ f_{2}(\bf{y}) \\ f_{3}(\bf{y}) \\ f_{4}(\bf{y}) \\ f_{5}(\bf{y}) \\ f_{6}(\bf{y}) \\ f_{7}(\bf{y}) \\ f_{8}(\bf{y}) \\ f_{9}(\bf{y}) \end{array}\right] = \left[ \begin{array}{c} 3x_{4}+4 x_{5} +4 x_{6} - 8 \\ 3 x_{1}+4 x_{2} -4 x_{3} \\ x_{7}x_{1} - x_{8} x_{2} -10 \\ x_{7}x_{4} - x_{8} x_{5} \\ x_{8}x_{2} + x_{9}x_{3} -20 \\ x_{8}x_{5}-x_{9}x_{6} \\ x_{1}^2+x_{4}^2-1 \\ x_{2}^2+x_{5}^2-1 \\ x_{3}^2+x_{6}^2-1 \end{array}\right] =0 
\end{equation}

Make a guess ($x_{1},...x_{9}$), and then correct it ($\Delta x_{1},...,\Delta x_{9}$), we have
\begin{equation}
f_{i}(x_{1}+\Delta x_{1}, x_{2}+\Delta x_{2}, ..., x_{9}+\Delta x_{9})=0 \qquad, i=1,...,9
\end{equation}
We can expand it using Taylor series
\begin{equation}
f_{i}(x_{1}+\Delta x_{1}, x_{2}+\Delta x_{2}, ..., x_{9}+\Delta x_{9})\simeq f_{i}(x_{1},...,x_{9})+\sum_{j=1}^{9}\frac{\partial f_{i}}{\partial x_{j}}\Delta x_{j}=0 \qquad i=1,...,9
\end{equation}

\begin{equation}
\left[ \begin{array}{c} f_{1}\\ f_{2}\\ \ddots \\ f_{9} \end{array}\right] + \begin{bmatrix} \partial f_{1}/\partial x_{1} & \partial f_{1}/\partial x_{2} & ... & \partial f_{1}/\partial x_{9} \\ \partial f_{2}/\partial x_{1} & \partial f_{2}/\partial x_{2} & ... & \partial f_{2}/\partial x_{9} \\ \ddots \\ \partial f_{9}/\partial x_{1} & \partial f_{9}/\partial x_{2} & ... & \partial f_{9}/\partial x_{9}\end{bmatrix}\left[ \begin{array}{c} \Delta x_{1} \\ \Delta x_{2} \\ \ddots \\ \Delta x_{9} \end{array}\right] =0 
\end{equation}

So we want to solve the matrix equation
\begin{equation}
F'\Delta {\bf{x}}=-\bf{f}
\end{equation}
Here we use bold font for a vector, the captal letter to represent a matrix

In [48]:
""" From "COMPUTATIONAL PHYSICS", 3rd Ed, Enlarged Python eTextBook  
    by RH Landau, MJ Paez, and CC Bordeianu
    Copyright Wiley-VCH Verlag GmbH & Co. KGaA, Berlin;  Copyright R Landau,
    Oregon State Unv, MJ Paez, Univ Antioquia, C Bordeianu, Univ Bucharest, 2015.
    Support by National Science Foundation"""

# NewtonNDanimate.py:      MultiDimension Newton Search
from numpy import *
from vpython import *
from numpy.linalg import solve


scene = canvas(title='String and masses configuration',
     width=500, height=500) # set the camera

tempe = curve(x=range(0,500),color=color.black)

n = 9
eps = 1e-3
deriv = zeros( (n, n), float)
f = zeros( (n), float)
x = array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1., 1., 1.])

def plotconfig():
    for obj in scene.objects:
        obj.visible=0                  # Erase previous configuration
    L1 = 3.0
    L2 = 4.0
    L3 = 4.0
    xa = L1*x[3]                # L1*cos(th1)
    ya = L1*x[0]                # L1 sin(th1)
    xb = xa+L2*x[4]             # L1*cos(th1)+L2*cos(th2)
    yb = ya+L2*x[1]             # L1*sin(th1)+L2*sen(th2)
    xc = xb+L3*x[5]             # L1*cos(th1)+L2*cos(th2)+L3*cos(th3)
    yc = yb-L3*x[2]             # L1*sin(th1)+L2*sen(th2)-L3*sin(th3)
    mx = 100.0                  # for linear coordinate transformation
    bx = -500.0                 # from 0=< x =<10
    my = -100.0                 # to    -500 =<x_window=>500
    by = 400.0                  # same transformation for y
    xap = mx*xa+bx              # to keep aspect ratio
    yap = my*ya+by
    ball1 = sphere(pos=vector(xap,yap,0), color=color.cyan,radius=15) 
    xbp = mx*xb+bx
    ybp = my*yb+by
    ball2 = sphere(pos=vector(xbp,ybp,0), color=color.cyan,radius=25) 
    xcp = mx*xc+bx
    ycp = my*yc+by
    x0 = mx*0+bx
    y0 = my*0+by
    line1 = curve(pos=[vector(x0,y0,0),vector(xap,yap,0)], color=color.yellow,radius=4)
    line2 = curve(pos=[vector(xap,yap,0),vector(xbp,ybp,0)], color=color.yellow,radius=4)
    line3 = curve(pos=[vector(xbp,ybp,0),vector(xcp,ycp,0)], color=color.yellow,radius=4)
    topline = curve(pos=[vector(x0,y0,0),vector(xcp,ycp,0)], color=color.red,radius=4)

def F(x, f):                                       # F function
    f[0] = 3*x[3]  +  4*x[4]  +  4*x[5]  -  8.0
    f[1] = 3*x[0]  +  4*x[1]  -  4*x[2]
    f[2] = x[6]*x[0]  -  x[7]*x[1]  -  10.0
    f[3] = x[6]*x[3]  -  x[7]*x[4]
    f[4] = x[7]*x[1]  +  x[8]*x[2]  -  20.0
    f[5] = x[7]*x[4]  -  x[8]*x[5]
    f[6] = pow(x[0], 2)  +  pow(x[3], 2)  -  1.0
    f[7] = pow(x[1], 2)  +  pow(x[4], 2)  -  1.0
    f[8] = pow(x[2], 2)  +  pow(x[5], 2)  -  1.0
    
def dFi_dXj(x, deriv, n):                           # Derivatives
    h = 1e-4                                             
    for j in range(0, n):
         temp = x[j]
         x[j] = x[j] +  h/2.
         F(x, f)                                                 
         for i in range(0, n):  deriv[i, j] = f[i] 
         x[j] = temp
    for j in range(0, n):
         temp = x[j]
         x[j] = x[j] - h/2.
         F(x, f)
         for i in range(0, n): deriv[i, j] = (deriv[i, j] - f[i])/h
         x[j] = temp
         
for it in range(1, 100):
      rate(1)                            # 1 second between graphs
      F(x, f)                              
      dFi_dXj(x, deriv, n)   
      B = array([[-f[0]], [-f[1]], [-f[2]], [-f[3]], [-f[4]], [-f[5]],\
			[-f[6]], [-f[7]], [-f[8]]])      
      sol = solve(deriv, B)
      dx = sol#take(sol, (0, ), 1)               # First column of sol
      for i in range(0, n):
        x[i]  = x[i]  +  dx[i]
      plotconfig()
      errX = errF = errXi = 0.0
      endi=0
      for i in range(0, n):
        if ( x[i] !=  0.): errXi = abs(dx[i]/x[i])
        else:  errXi = abs(dx[i])
        if ( errXi > errX): errX = errXi                            
        if ( abs(f[i]) > errF ):  errF = abs(f[i])        
        if ( (errX <=  eps) and (errF <=  eps) ): endi=1
      if(endi==1): break  
      
print('Number of iterations = ', it, "\n Final Solution:")
for i in range(0, n):
        print('x[', i, '] =  ', x[i])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Number of iterations =  8 
 Final Solution:
x[ 0 ] =   0.7610026986802355
x[ 1 ] =   0.26495380629721876
x[ 2 ] =   0.8357058303073954
x[ 3 ] =   0.6487487163497033
x[ 4 ] =   0.9642611069149696
x[ 5 ] =   0.5491773558227533
x[ 6 ] =   17.160209645431618
x[ 7 ] =   11.54527961917644
x[ 8 ] =   20.2715779893147


In [50]:
""" From "COMPUTATIONAL PHYSICS", 3rd Ed, Enlarged Python eTextBook  
    by RH Landau, MJ Paez, and CC Bordeianu
    Copyright Wiley-VCH Verlag GmbH & Co. KGaA, Berlin;  Copyright R Landau,
    Oregon State Unv, MJ Paez, Univ Antioquia, C Bordeianu, Univ Bucharest, 2015.
    Support by National Science Foundation"""

# NewtonNDanimate.py:      MultiDimension Newton Search
from numpy import *
from vpython import *
from numpy.linalg import solve


scene = canvas(title='String and masses configuration',
     width=500, height=500) # set the camera

tempe = curve(x=range(0,500),color=color.black)

n = 9
eps = 1e-3
deriv = zeros( (n, n), float)
f = zeros( (n), float)
x = array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1., 1., 1.])

def plotconfig(a):
    for obj in scene.objects:
        obj.visible=0                  # Erase previous configuration
    L1 = 3.0
    L2 = a
    L3 = 4.0
    xa = L1*x[3]                # L1*cos(th1)
    ya = L1*x[0]                # L1 sin(th1)
    xb = xa+L2*x[4]             # L1*cos(th1)+L2*cos(th2)
    yb = ya+L2*x[1]             # L1*sin(th1)+L2*sen(th2)
    xc = xb+L3*x[5]             # L1*cos(th1)+L2*cos(th2)+L3*cos(th3)
    yc = yb-L3*x[2]             # L1*sin(th1)+L2*sen(th2)-L3*sin(th3)
    mx = 100.0                  # for linear coordinate transformation
    bx = -500.0                 # from 0=< x =<10
    my = -100.0                 # to    -500 =<x_window=>500
    by = 400.0                  # same transformation for y
    xap = mx*xa+bx              # to keep aspect ratio
    yap = my*ya+by
    ball1 = sphere(pos=vector(xap,yap,0), color=color.cyan,radius=15) 
    print(xap,yap)
    xbp = mx*xb+bx
    ybp = my*yb+by
    ball2 = sphere(pos=vector(xbp,ybp,0), color=color.cyan,radius=25) 
    xcp = mx*xc+bx
    ycp = my*yc+by
    x0 = mx*0+bx
    y0 = my*0+by
    line1 = curve(pos=[vector(x0,y0,0),vector(xap,yap,0)], color=color.yellow,radius=4)
    line2 = curve(pos=[vector(xap,yap,0),vector(xbp,ybp,0)], color=color.yellow,radius=4)
    line3 = curve(pos=[vector(xbp,ybp,0),vector(xcp,ycp,0)], color=color.yellow,radius=4)
    topline = curve(pos=[vector(x0,y0,0),vector(xcp,ycp,0)], color=color.red,radius=4)

def F(x, f, a):                                       # F function
    f[0] = 3*x[3]  +  a*x[4]  +  4*x[5]  -  8.0
    f[1] = 3*x[0]  +  a*x[1]  -  4*x[2]
    f[2] = x[6]*x[0]  -  x[7]*x[1]  -  10.0
    f[3] = x[6]*x[3]  -  x[7]*x[4]
    f[4] = x[7]*x[1]  +  x[8]*x[2]  -  20.0
    f[5] = x[7]*x[4]  -  x[8]*x[5]
    f[6] = pow(x[0], 2)  +  pow(x[3], 2)  -  1.0
    f[7] = pow(x[1], 2)  +  pow(x[4], 2)  -  1.0
    f[8] = pow(x[2], 2)  +  pow(x[5], 2)  -  1.0
    
def dFi_dXj(x, deriv, n, a):                           # Derivatives
    h = 1e-4                                             
    for j in range(0, n):
         temp = x[j]
         x[j] = x[j] +  h/2.
         F(x, f, a)                                                 
         for i in range(0, n):  deriv[i, j] = f[i] 
         x[j] = temp
    for j in range(0, n):
         temp = x[j]
         x[j] = x[j] - h/2.
         F(x, f, a)
         for i in range(0, n): deriv[i, j] = (deriv[i, j] - f[i])/h
         x[j] = temp
         
for a in arange(2.,10.,0.1):
  for it in range(1, 100):
      rate(10)                    # 1 second between graphs
      F(x, f, a )                              
      dFi_dXj(x, deriv, n, a)   
      B = array([[-f[0]], [-f[1]], [-f[2]], [-f[3]], [-f[4]], [-f[5]],\
			[-f[6]], [-f[7]], [-f[8]]])      
      sol = solve(deriv, B)
      dx = sol#take(sol, (0, ), 1)               # First column of sol
      for i in range(0, n):
        x[i]  = x[i]  +  dx[i]
      errX = errF = errXi = 0.0
      endi=0
      for i in range(0, n):
        if ( x[i] !=  0.): errXi = abs(dx[i]/x[i])
        else:  errXi = abs(dx[i])
        if ( errXi > errX): errX = errXi                            
        if ( abs(f[i]) > errF ):  errF = abs(f[i])        
        if ( (errX <=  eps) and (errF <=  eps) ): endi=1
      if(endi==1): break   
  plotconfig(a)

print('Number of iterations = ', it, "\n Final Solution:")
for i in range(0, n):
        print('x[', i, '] =  ', x[i])

<IPython.core.display.Javascript object>

-254.1605248112708-270.3313053319125 206.99145474621324
-276.3539127133266-279.30011956894396 196.7967353307992
-305.37540336122663 171.69917425424597-314.5764975932673 164.1650456635142
-321.0547225273583 159.21256469382584
-324.4206219341606-338.8805870670551 146.9376809541126
-342.769584455115-350.8988481726788-363.98321134539333 132.6062144793852
-373.2879421155345 128.07343313107674
-383.0320889374185-388.0589050771857-398.3983397687487-409.0844748257484 114.10776392443694
-414.5442709083077 112.42857975839945
-466.26618805345174 -472.21580054407195-484.18876332804155-502.28291935939194-514.4004936193191 -532.6055799475217-556.8330263160927 105.43250160090213
-562.867102765279-586.8510996680945-592.7991631417622-610.496990400636 121.0906606799943
Number of iterations =  2 
 Final Solution:
x[ 0 ] =   0.9296977977333524
x[ 1 ] =   0.1155523779645883
x[ 2 ] =   0.9832654837623704
x[ 3 ] =   -0.3683233013354535
x[ 4 ] =   0.9933013892183487
x[ 5 ] =   -0.18217846231382495
x[ 6 ] =   




## 2) Solve the eigenvalue problem
\begin{equation}
A\bf{x}=\lambda\bf{x}
\end{equation}
where $\bf{x}$ is an unknown vector and $\lambda$ is an unknown parameter. Using the above method won't work since we have unknowns on both sides of the equation.

This is harder to solve, since the solution only exists for certain, if any, values of $\lambda$. We manipulate the equation
\begin{equation}
[A-\lambda I]\bf{x}=0
\end{equation}
If $[A-\lambda I]^{-1}$ exists, it leads to the trivial solution $\bf{x}=0$. The inverse of $[A-\lambda I]$ fails to exists if 
\begin{equation}
det[A-\lambda I]=0
\end{equation}
The $\lambda$ values satisfie this equation are the eigenvalues.  If you are only interested in eigenvalues, you need to calculate the determinant first and search $\lambda$ to make the equation equal 0.  

The traditional way to solve both the eigenvalues and the eigenvectors is diagonalization. Gradually change A to a diagonal 
\begin{equation}
UAU^{-1}=\begin{bmatrix} \lambda^{'}_{1} & 0 & ... &0 \\ 0 & \lambda^{'}_{2} & ... & 0 \\ 0 & 0 & \lambda^{'}_{3} & ... \\ 0 & ... &0 &\lambda^{'}_{N} \end{bmatrix}
\end{equation}
\begin{equation}
UA(U^{-1}U)\bf{x}=\lambda U\bf{x}
\end{equation}
\begin{equation}
\begin{bmatrix} \lambda^{'}_{1} & 0 & ... &0 \\ 0 & \lambda^{'}_{2} & ... & 0 \\ 0 & 0 & \lambda^{'}_{3} & ... \\ 0 & ... &0 &\lambda^{'}_{N} \end{bmatrix} U\bf{x} = \lambda U\bf{x}
\end{equation}
The first eigenvalue is $\lambda^{'}_{1}$ and the first eigenvector (U$\bf{x}$) is $(1,0,...)$, ...  
So $\bf{x}$ is $U^{-1}\hat{e_{1}}$. Overal the eigenvalues are $\lambda^{'}_{i}$ and the eigenvectors are 
\begin{equation}
\bf{x_{i}}=U^{-1}\hat{e_{i}}
\end{equation}
That is the eigenvectors are the columns of the matrix $U^{-1}$

### Solve eigenvalue problem

In [51]:
import numpy as np
I=np.array([[2./3.,-1./4.],[-1./4.,2./3.]])
print(I)
eigenvalues, eigenmatrix = np.linalg.eig(I)
print('Eigenvalues', eigenvalues, '\n Eigenmatrix', eigenmatrix)
print('Eigenvector',eigenmatrix[:,0],eigenmatrix[:,1])

[[ 0.66666667 -0.25      ]
 [-0.25        0.66666667]]
Eigenvalues [0.91666667 0.41666667] 
 Eigenmatrix [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Eigenvector [ 0.70710678 -0.70710678] [0.70710678 0.70710678]


In [52]:
eigenvector1=np.array([eigenmatrix[0,0],eigenmatrix[1,0]])
LHS = np.dot(I,eigenvector1)
RHS = eigenvector1*eigenvalues[0]
print('LHS-RHS',LHS-RHS)

print(eigenvector1)
# an easier way to get the first coloumn
print(eigenmatrix[:,0])

LHS-RHS [ 1.11022302e-16 -1.11022302e-16]
[ 0.70710678 -0.70710678]
[ 0.70710678 -0.70710678]


In [58]:
# Find the eigenvalue and eigenvector for ([1,-3,3],[3,-5,3],[6,-6,4])

# Now double check that the derived eigenvalue and eigenvector can satisfy Ax=\lamba x


[[ 1. -3.  3.]
 [ 3. -5.  3.]
 [ 6. -6.  4.]]
Eigenvalues [ 4. -2. -2.] 
 Eigenmatrix [[-0.40824829 -0.81034214  0.1932607 ]
 [-0.40824829 -0.31851537 -0.59038328]
 [-0.81649658  0.49182677 -0.78364398]]
Eigenvector [-0.40824829 -0.40824829 -0.81649658] [-0.81034214 -0.31851537  0.49182677] [ 0.1932607  -0.59038328 -0.78364398]
[-1.63299316 -1.63299316 -3.26598632] [-1.63299316 -1.63299316 -3.26598632]
[ 1.62068428  0.63703074 -0.98365355] [ 1.62068428  0.63703074 -0.98365355]
[-0.38652141  1.18076655  1.56728796] [-0.38652141  1.18076655  1.56728796]


In [62]:
#Homework: Use the linalg package, LU decompositin, and GaussSeidel method to solve 2y+z=-8, x-2y-3z=0, -x+y+2z=3

Homeworks are due next Tuesday 11:59 pm.

x= [-4. -5.  2.]
Time  0.0001659393310546875
x= [-4. -5.  2.]
Time  0.0483851432800293
x= [-4. -5.  2.]
Time  0.00019288063049316406


In [69]:
# Homework for graduate students:
# Solve equation array dx/dt=x-(1/8)y, dy/dt=-2x+y.  Write down the analytical solution 
# (coefficients can be floating point numbers)
# Hint: first use linalg to get the eigenvalue and eigenvector for [[1,-1/3],[-2,1]] array

Homeworks are due next Tuesday 11:59 pm.

[[ 1.    -0.125]
 [-2.     1.   ]]
Eigenvalues [1.5 0.5] 
 Eigenmatrix [[ 0.24253563  0.24253563]
 [-0.9701425   0.9701425 ]]
Eigenvector [ 0.24253563 -0.9701425 ] [0.24253563 0.9701425 ]
